[package]
name = "rave"
version = "0.1.0"
edition = "2021"

[dependencies]
circular-buffer = "0.1.7"
cpal = "0.15.3"
derive_more = { version = "1.0.0", features = ["deref", "deref_mut"] }
hound = "3.5.1"
ringbuf = "0.4.4"
rustfft = "6.2.0"
softbuffer = "0.4.6"
tiny-skia = "0.11.4"
winit = "0.30.5"
